### ISSUE TITLE
Patch the script for a folder name with a space.

### ISSUE THREAD

**Issue by ZerooCool** [famavott/osint-scraper#159]
If i create the folder /home/user/Social Recon/
Then, i git clone ...

I have a error with this commande : source ENV/bin/activate

Can't found the folder  /home/user/Social

Or the folder is : Social Recon

Patch the script for a folder name with a space.

**Comment by gabrielx52** [comment]
Why don't you just change Social Recon to SocialRecon or Social_Recon or Social-Recon?

**Comment by ZerooCool** [comment]
Hi, yes i have.
I open a issue then you can make the script better ?

**Comment by gabrielx52** [comment]
The error you are having isn't caused by our script, it looks like a problem with your virtual environment or directory setup.

**Comment by ZerooCool** [comment]
Hummm, ah ok. Sorry.
The script can't force that ? Ok ...
I don't no, how i can make better, then, i use Social-Recon, not use Social Recon.
Resolved, but, i don't anderstand where is the problem.
