### ISSUE TITLE
Add clear installation/usage instructions

### ISSUE THREAD

**Issue by alichtman** [famavott/osint-scraper#166]
On OS X 10.13.4, I had to run this series of commands to get this program to not error. 

Would you consider adding these to the README in a USAGE section?

```shell
virtualenv venv
. venv/bin/activate
pip3 install -r requirements.txt
pip3 install -e .
pserve development.ini
```

**Comment by famavott** [comment]
@alichtman I added clarification to set up a virualenv, and also included instructions to use `pip install -r requirements.txt` if that is the method devs choose to get all dependencies for the repo. Thanks.
